import { Box, Button, Flex, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect, useState } from "react";

import Article from "../components/Article";
import { useStateContext } from "../context/StateContext";
import { API } from "../redux/userSlice";

export default function Home({ articles, categories }) {
   const { text, filteredArticles, setFilteredArticles } = useStateContext();
   useEffect(() => {
      setFilteredArticles(articles);
   }, [articles]);

   useEffect(() => {
      if (text?.length > 3) {
         const filtered = articles.filter((article) => {
            return article.title.toLowerCase().includes(text.toLowerCase());
         });
         setFilteredArticles(filtered);
      } else {
         setFilteredArticles(articles);
      }
   }, [text, articles]);

   const handleFilter = (value) => {
      if (value === "All") {
         setFilteredArticles(articles);
      } else {
         const filtered = articles.filter((article) => {
            return article.category.toLowerCase().includes(value.toLowerCase());
         });
         setFilteredArticles(filtered);
      }
   };
   return (
      <>
         <Head>
            <title>Articles</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Flex justifyContent="center" gap="5" mt="5">
            {[...categories].map((category) => (
               <>
                  <Button key={category._id} cursor="pointer" onClick={() => handleFilter(category.name || "All")}>
                     {category.name}
                  </Button>
               </>
            ))}
            <Button cursor="pointer" onClick={() => handleFilter("All")}>
               All
            </Button>
         </Flex>
         <Box>
            <Flex flexWrap={"wrap"} justifyContent="center">
               {filteredArticles?.map((article, index) => (
                  <Article key={index} article={article} />
               ))}
            </Flex>
         </Box>
      </>
   );
}

export const getServerSideProps = async () => {
   const { data } = await API.get("/articles");
   const res = await API.get("/category");
   const categories = res.data;
   return {
      props: {
         articles: data,
         categories,
      },
   };
};
